- name: openssh_server_upgrade | Update the repository cache and upgrade package "OpenSSH-server" to latest version
  apt:
    name: "{{ openssh_server_package_name }}" 
    state: latest
    update_cache: yes
  when: >
    ansible_os_family | lower == "debian"

- name: openssh_server_upgrade | Update the repository cache and upgrade package "OpenSSH-server" to latest version
  dnf:
    name: "{{ openssh_server_package_name }}" 
    state: latest
    update_cache: yes
  when: >
    ansible_os_family | lower == "redhat" and
    ansible_distribution_major_version >= '8'

- name: openssh_server_upgrade | Update the repository cache and upgrade package "OpenSSH-server" to latest version
  yum:
    name: "{{ openssh_server_package_name }}" 
    state: latest
    update_cache: yes
  when: >
    ansible_os_family | lower == "redhat" and
    ansible_distribution_major_version < '8'
